{{- $fullName := include "mychart.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "mychart.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.lb.type }}
    {{- if (regexFind ".*nginx.*" .Values.lb.type) }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- if (regexFind ".*azure.*" .Values.lb.type) }}
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Values.namespace }}
    cert-manager.io/acme-challenge-type: http01
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- range $key, $value := .Values.lb.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
    - hosts:
    {{- range .Values.lb.hosts }}
        - {{ if and $.Values.branchRelease $.Values.branchName }}{{ $.Values.branchName }}-{{end}}{{ .host }}
    {{- end }}
  rules:
  {{- range .Values.lb.hosts }}
    - host: {{ if and $.Values.branchRelease $.Values.branchName }}{{ $.Values.branchName }}-{{end}}{{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
  {{- end }}