apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
{{ include "mychart.labels" . | indent 4 }}
spec:
  type: {{ if .Values.service.type }}{{ .Values.service.type }}{{ else }}{{ if regexFind ".*type:alb.*" (printf "%s" .Values.lb) }}NodePort{{ else }}ClusterIP{{ end }}{{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range .Values.extraServicePorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol:  {{ .protocol  }}
      name: {{ .name }}   
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "mychart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
